
let mockNftData = [
    {
        id: 1,
        name: "CryptoPunk #7804",
        collection: "CryptoPunks",
        image: "./resources/nft-1.jpg",
        price: "24.5",
        currency: "ETH",
        owner: "0x742d35Cc6634C0532925a3b8D4C0C8b3C",
        creator: "0x742d35Cc6634C0532925a3b8D4C0C8b3C",
        attributes: ["Alien", "Pipe", "Cap"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 1247,
        views: 8932,
        isNew: false,
        isTrending: true,
        description: "One of the rarest CryptoPunks with alien skin and unique accessories."
    },
    {
        id: 2,
        name: "Azuki #4521",
        collection: "Azuki",
        image: "./resources/nft-2.jpg",
        price: "8.2",
        currency: "ETH",
        owner: "0x8ba1f109551bD432803012645Hac136c",
        creator: "0x8ba1f109551bD432803012645Hac136c",
        attributes: ["Red Kimono", "Sword", "Spirit"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 892,
        views: 5421,
        isNew: false,
        isTrending: true,
        description: "A mystical Azuki warrior with powerful spiritual energy."
    },
    {
        id: 3,
        name: "Polygon Master #89",
        collection: "Polygon Masters",
        image: "./resources/nft-3.jpg",
        price: "2.1",
        currency: "ETH",
        owner: "0x3f5E5B8d3B2A1C9E8F7D6C5B4A3",
        creator: "0x3f5E5B8d3B2A1C9E8F7D6C5B4A3",
        attributes: ["Blue", "Geometric", "Abstract"],
        chain: "polygon",
        category: "art",
        status: "auction",
        likes: 456,
        views: 2341,
        isNew: true,
        isTrending: false,
        description: "Geometric abstraction representing the future of blockchain art."
    },
    {
        id: 4,
        name: "Digital Dream #156",
        collection: "Digital Dreams",
        image: "./resources/nft-4.jpg",
        price: "1.8",
        currency: "ETH",
        owner: "0x9c2f3E8d1B4A5C7D9E6F3A2B1",
        creator: "0x9c2f3E8d1B4A5C7D9E6F3A2B1",
        attributes: ["Abstract", "Colorful", "Dynamic"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 234,
        views: 1876,
        isNew: true,
        isTrending: false,
        description: "A vibrant digital dreamscape with flowing colors and shapes."
    },
    {
        id: 5,
        name: "Solana Warrior #23",
        collection: "Solana Warriors",
        image: "./resources/nft-5.jpg",
        price: "15.7",
        currency: "SOL",
        owner: "0x7a8B9c3D2E1F4G6H5J4K3L2M1",
        creator: "0x7a8B9c3D2E1F4G6H5J4K3L2M1",
        attributes: ["Warrior", "Armor", "Sword"],
        chain: "solana",
        category: "gaming",
        status: "buy-now",
        likes: 678,
        views: 3456,
        isNew: false,
        isTrending: true,
        description: "A fierce warrior from the Solana blockchain realm."
    },
    {
        id: 6,
        name: "Blockchain Art #77",
        collection: "Blockchain Arts",
        image: "./resources/nft-6.jpg",
        price: "3.4",
        currency: "ETH",
        owner: "0x4e5F6G7H8I9J0K1L2M3N4O5P6",
        creator: "0x4e5F6G7H8I9J0K1L2M3N4O5P6",
        attributes: ["Modern", "Conceptual", "Digital"],
        chain: "ethereum",
        category: "art",
        status: "new",
        likes: 345,
        views: 2123,
        isNew: true,
        isTrending: false,
        description: "Modern conceptual art piece exploring digital ownership."
    },
    {
        id: 7,
        name: "Moonbird #892",
        collection: "Moonbirds",
        image: "./resources/nft-7.jpg",
        price: "12.3",
        currency: "ETH",
        owner: "0x5g6H7I8J9K0L1M2N3O4P5Q6R7",
        creator: "0x5g6H7I8J9K0L1M2N3O4P5Q6R7",
        attributes: ["Ruby", "Cosmic", "Mystical"],
        chain: "ethereum",
        category: "art",
        status: "offers",
        likes: 567,
        views: 2987,
        isNew: false,
        isTrending: true,
        description: "A mystical moonbird with cosmic ruby feathers."
    },
    {
        id: 8,
        name: "Polygon Genesis #45",
        collection: "Polygon Genesis",
        image: "./resources/nft-8.jpg",
        price: "4.7",
        currency: "ETH",
        owner: "0x6h7I8J9K0L1M2N3O4P5Q6R7S8",
        creator: "0x6h7I8J9K0L1M2N3O4P5Q6R7S8",
        attributes: ["Genesis", "Rare", "Animated"],
        chain: "polygon",
        category: "art",
        status: "buy-now",
        likes: 289,
        views: 1654,
        isNew: true,
        isTrending: false,
        description: "Genesis piece from the Polygon blockchain collection."
    },
    {
        id: 9,
        name: "Azuki Spirit #234",
        collection: "Azuki Spirits",
        image: "./resources/nft-9.jpg",
        price: "6.8",
        currency: "ETH",
        owner: "0x7i8J9K0L1M2N3O4P5Q6R7S8T9",
        creator: "0x7i8J9K0L1M2N3O4P5Q6R7S8T9",
        attributes: ["Spirit", "Ethereal", "Blue"],
        chain: "ethereum",
        category: "art",
        status: "auction",
        likes: 445,
        views: 2876,
        isNew: false,
        isTrending: false,
        description: "An ethereal spirit from the Azuki universe."
    },
    {
        id: 10,
        name: "Ethereum Classic #11",
        collection: "Ethereum Classics",
        image: "./resources/nft-10.jpg",
        price: "7.9",
        currency: "ETH",
        owner: "0x8j9K0L1M2N3O4P5Q6R7S8T9U0",
        creator: "0x8j9K0L1M2N3O4P5Q6R7S8T9U0",
        attributes: ["Classic", "Vintage", "Historic"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 334,
        views: 1987,
        isNew: false,
        isTrending: false,
        description: "A classic piece representing the history of Ethereum."
    },
    {
        id: 11,
        name: "Crypto Punkette #156",
        collection: "Crypto Punkettes",
        image: "./resources/nft-11.jpg",
        price: "18.9",
        currency: "ETH",
        owner: "0x9k0L1M2N3O4P5Q6R7S8T9U0V1",
        creator: "0x9k0L1M2N3O4P5Q6R7S8T9U0V1",
        attributes: ["Female", "Earrings", "Red Lipstick"],
        chain: "ethereum",
        category: "art",
        status: "offers",
        likes: 756,
        views: 4234,
        isNew: false,
        isTrending: true,
        description: "A rare female CryptoPunk with distinctive accessories."
    },
    {
        id: 12,
        name: "Pixel Master #78",
        collection: "Pixel Masters",
        image: "./resources/nft-12.jpg",
        price: "2.3",
        currency: "ETH",
        owner: "0x0l1M2N3O4P5Q6R7S8T9U0V1W2",
        creator: "0x0l1M2N3O4P5Q6R7S8T9U0V1W2",
        attributes: ["Pixel", "8-bit", "Retro"],
        chain: "ethereum",
        category: "art",
        status: "new",
        likes: 198,
        views: 1234,
        isNew: true,
        isTrending: false,
        description: "8-bit retro pixel art masterpiece."
    },
    {
        id: 13,
        name: "Digital Artist #42",
        collection: "Digital Artists",
        image: "./resources/nft-13.jpg",
        price: "5.6",
        currency: "ETH",
        owner: "0x1m2N3O4P5Q6R7S8T9U0V1W2X3",
        creator: "0x1m2N3O4P5Q6R7S8T9U0V1W2X3",
        attributes: ["Artist", "Creative", "Modern"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 412,
        views: 2567,
        isNew: false,
        isTrending: false,
        description: "Modern digital art representing creative expression."
    },
    {
        id: 14,
        name: "Future Vision #99",
        collection: "Future Visions",
        image: "./resources/nft-14.jpg",
        price: "9.1",
        currency: "ETH",
        owner: "0x2n3O4P5Q6R7S8T9U0V1W2X3Y4",
        creator: "0x2n3O4P5Q6R7S8T9U0V1W2X3Y4",
        attributes: ["Future", "Vision", "Sci-fi"],
        chain: "ethereum",
        category: "art",
        status: "auction",
        likes: 567,
        views: 3456,
        isNew: false,
        isTrending: false,
        description: "A sci-fi vision of the future in digital form."
    },
    {
        id: 15,
        name: "NFT Trading Card #33",
        collection: "NFT Trading Cards",
        image: "./resources/nft-15.jpg",
        price: "1.2",
        currency: "ETH",
        owner: "0x3o4P5Q6R7S8T9U0V1W2X3Y4Z5",
        creator: "0x3o4P5Q6R7S8T9U0V1W2X3Y4Z5",
        attributes: ["Trading", "Card", "Collectible"],
        chain: "ethereum",
        category: "gaming",
        status: "buy-now",
        likes: 234,
        views: 1678,
        isNew: true,
        isTrending: false,
        description: "Rare trading card from the NFT gaming universe."
    },
    {
        id: 16,
        name: "Azuki Warrior #167",
        collection: "Azuki Warriors",
        image: "./resources/nft-16.jpg",
        price: "11.4",
        currency: "ETH",
        owner: "0x4p5Q6R7S8T9U0V1W2X3Y4Z5A6",
        creator: "0x4p5Q6R7S8T9U0V1W2X3Y4Z5A6",
        attributes: ["Warrior", "Katana", "Armor"],
        chain: "ethereum",
        category: "art",
        status: "offers",
        likes: 489,
        views: 2765,
        isNew: false,
        isTrending: false,
        description: "A skilled warrior from the Azuki collection."
    },
    {
        id: 17,
        name: "Digital Landscape #58",
        collection: "Digital Landscapes",
        image: "./resources/nft-17.jpg",
        price: "3.7",
        currency: "ETH",
        owner: "0x5q6R7S8T9U0V1W2X3Y4Z5A6B7",
        creator: "0x5q6R7S8T9U0V1W2X3Y4Z5A6B7",
        attributes: ["Landscape", "Nature", "Digital"],
        chain: "ethereum",
        category: "art",
        status: "new",
        likes: 356,
        views: 2134,
        isNew: true,
        isTrending: false,
        description: "Beautiful digital landscape capturing nature's essence."
    },
    {
        id: 18,
        name: "Moonbird Mystic #445",
        collection: "Moonbird Mystics",
        image: "./resources/nft-18.jpg",
        price: "16.8",
        currency: "ETH",
        owner: "0x6r7S8T9U0V1W2X3Y4Z5A6B7C8",
        creator: "0x6r7S8T9U0V1W2X3Y4Z5A6B7C8",
        attributes: ["Mystic", "Magical", "Enchanted"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 623,
        views: 3678,
        isNew: false,
        isTrending: true,
        description: "A mystical moonbird with magical enchanted powers."
    },
    {
        id: 19,
        name: "Crypto Artist #89",
        collection: "Crypto Artists",
        image: "./resources/nft-19.jpg",
        price: "4.2",
        currency: "ETH",
        owner: "0x7s8T9U0V1W2X3Y4Z5A6B7C8D9",
        creator: "0x7s8T9U0V1W2X3Y4Z5A6B7C8D9",
        attributes: ["Artist", "Creative", "Unique"],
        chain: "ethereum",
        category: "art",
        status: "auction",
        likes: 278,
        views: 1876,
        isNew: false,
        isTrending: false,
        description: "Unique crypto art representing creative innovation."
    },
    {
        id: 20,
        name: "Digital Masterpiece #1",
        collection: "Digital Masterpieces",
        image: "./resources/nft-20.jpg",
        price: "28.9",
        currency: "ETH",
        owner: "0x8t9U0V1W2X3Y4Z5A6B7C8D9E0",
        creator: "0x8t9U0V1W2X3Y4Z5A6B7C8D9E0",
        attributes: ["Masterpiece", "Premium", "Exclusive"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 834,
        views: 5432,
        isNew: false,
        isTrending: true,
        description: "An exclusive digital masterpiece of premium quality."
    },
    {
        id: 21,
        name: "Pixel Warrior #101",
        collection: "Pixel Warriors",
        image: "./resources/nft-21.png",
        price: "1.5",
        currency: "ETH",
        owner: "0x9k1L2M3N4O5P6Q7R8S9T0U1V2",
        creator: "0x9k1L2M3N4O5P6Q7R8S9T0U1V2",
        attributes: ["Pixel", "Warrior", "8-bit"],
        chain: "ethereum",
        category: "gaming",
        status: "new",
        likes: 189,
        views: 1456,
        isNew: true,
        isTrending: false,
        description: "8-bit pixel warrior ready for battle."
    },
    {
        id: 22,
        name: "Abstract Mind #77",
        collection: "Abstract Minds",
        image: "./resources/nft-22.jpeg",
        price: "3.2",
        currency: "ETH",
        owner: "0x0l2M3N4O5P6Q7R8S9T0U1V2W3",
        creator: "0x0l2M3N4O5P6Q7R8S9T0U1V2W3",
        attributes: ["Abstract", "Mind", "Colorful"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 298,
        views: 1876,
        isNew: false,
        isTrending: false,
        description: "Abstract representation of the creative mind."
    },
    {
        id: 23,
        name: "Digital Canvas #45",
        collection: "Digital Canvases",
        image: "./resources/nft-23.jpg",
        price: "2.8",
        currency: "ETH",
        owner: "0x1m3N4O5P6Q7R8S9T0U1V2W3X4",
        creator: "0x1m3N4O5P6Q7R8S9T0U1V2W3X4",
        attributes: ["Canvas", "Digital", "Art"],
        chain: "ethereum",
        category: "art",
        status: "auction",
        likes: 412,
        views: 2567,
        isNew: false,
        isTrending: false,
        description: "A beautiful digital canvas painting."
    },
    {
        id: 24,
        name: "Art Collection #88",
        collection: "Art Collections",
        image: "./resources/nft-24.png",
        price: "4.5",
        currency: "ETH",
        owner: "0x2n4O5P6Q7R8S9T0U1V2W3X4Y5",
        creator: "0x2n4O5P6Q7R8S9T0U1V2W3X4Y5",
        attributes: ["Collection", "Art", "Premium"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 567,
        views: 3456,
        isNew: false,
        isTrending: true,
        description: "Premium art collection piece."
    },
    {
        id: 25,
        name: "Music Vibes #66",
        collection: "Music Vibes",
        image: "./resources/nft-25.jpg",
        price: "1.9",
        currency: "ETH",
        owner: "0x3o5P6Q7R8S9T0U1V2W3X4Y5Z6",
        creator: "0x3o5P6Q7R8S9T0U1V2W3X4Y5Z6",
        attributes: ["Music", "Vibes", "Sound"],
        chain: "ethereum",
        category: "music",
        status: "new",
        likes: 234,
        views: 1678,
        isNew: true,
        isTrending: false,
        description: "Musical vibes captured in digital form."
    },
    {
        id: 26,
        name: "Celebrity Star #99",
        collection: "Celebrity Stars",
        image: "./resources/nft-26.jpg",
        price: "12.3",
        currency: "ETH",
        owner: "0x4p6Q7R8S9T0U1V2W3X4Y5Z6A7",
        creator: "0x4p6Q7R8S9T0U1V2W3X4Y5Z6A7",
        attributes: ["Celebrity", "Star", "Famous"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 789,
        views: 4321,
        isNew: false,
        isTrending: true,
        description: "Famous celebrity captured as digital art."
    },
    {
        id: 27,
        name: "Pixel Art Classic #12",
        collection: "Pixel Art Classics",
        image: "./resources/nft-27.png",
        price: "0.8",
        currency: "ETH",
        owner: "0x5q7R8S9T0U1V2W3X4Y5Z6A7B8",
        creator: "0x5q7R8S9T0U1V2W3X4Y5Z6A7B8",
        attributes: ["Pixel", "Classic", "Retro"],
        chain: "ethereum",
        category: "art",
        status: "auction",
        likes: 156,
        views: 987,
        isNew: false,
        isTrending: false,
        description: "Classic pixel art with retro styling."
    },
    {
        id: 28,
        name: "Abstract Dreams #34",
        collection: "Abstract Dreams",
        image: "./resources/nft-28.png",
        price: "2.7",
        currency: "ETH",
        owner: "0x6r8S9T0U1V2W3X4Y5Z6A7B8C9",
        creator: "0x6r8S9T0U1V2W3X4Y5Z6A7B8C9",
        attributes: ["Abstract", "Dreams", "Colorful"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 345,
        views: 2134,
        isNew: false,
        isTrending: false,
        description: "Colorful abstract dreams in digital form."
    },
    {
        id: 29,
        name: "3D Masterpiece #56",
        collection: "3D Masterpieces",
        image: "./resources/nft-29.png",
        price: "6.4",
        currency: "ETH",
        owner: "0x7s9T0U1V2W3X4Y5Z6A7B8C9D0",
        creator: "0x7s9T0U1V2W3X4Y5Z6A7B8C9D0",
        attributes: ["3D", "Masterpiece", "Sculpture"],
        chain: "ethereum",
        category: "art",
        status: "new",
        likes: 467,
        views: 2890,
        isNew: true,
        isTrending: false,
        description: "Stunning 3D digital sculpture masterpiece."
    },
    {
        id: 30,
        name: "Crypto Universe #23",
        collection: "Crypto Universes",
        image: "./resources/nft-30.jpg",
        price: "3.8",
        currency: "ETH",
        owner: "0x8t0U1V2W3X4Y5Z6A7B8C9D0E1",
        creator: "0x8t0U1V2W3X4Y5Z6A7B8C9D0E1",
        attributes: ["Universe", "Crypto", "Art"],
        chain: "ethereum",
        category: "art",
        status: "auction",
        likes: 289,
        views: 1654,
        isNew: false,
        isTrending: false,
        description: "The entire crypto universe in one digital piece."
    },
    {
        id: 31,
        name: "Pixel Corner #78",
        collection: "Pixel Corners",
        image: "./resources/nft-31.png",
        price: "1.1",
        currency: "ETH",
        owner: "0x9u1V2W3X4Y5Z6A7B8C9D0E1F2",
        creator: "0x9u1V2W3X4Y5Z6A7B8C9D0E1F2",
        attributes: ["Pixel", "Corner", "Art"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 198,
        views: 1234,
        isNew: false,
        isTrending: false,
        description: "Pixel art from the corner of the digital world."
    },
    {
        id: 32,
        name: "Music Beat #89",
        collection: "Music Beats",
        image: "./resources/nft-32.png",
        price: "2.4",
        currency: "ETH",
        owner: "0x0v2W3X4Y5Z6A7B8C9D0E1F2G3",
        creator: "0x0v2W3X4Y5Z6A7B8C9D0E1F2G3",
        attributes: ["Music", "Beat", "Rhythm"],
        chain: "ethereum",
        category: "music",
        status: "new",
        likes: 234,
        views: 1567,
        isNew: true,
        isTrending: false,
        description: "The rhythm and beat of music captured as NFT."
    },
    {
        id: 33,
        name: "Animal Kingdom #45",
        collection: "Animal Kingdoms",
        image: "./resources/nft-33.jpg",
        price: "1.7",
        currency: "ETH",
        owner: "0x1w3X4Y5Z6A7B8C9D0E1F2G3H4",
        creator: "0x1w3X4Y5Z6A7B8C9D0E1F2G3H4",
        attributes: ["Animal", "Kingdom", "Nature"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 345,
        views: 2134,
        isNew: false,
        isTrending: false,
        description: "Beautiful animal from the digital kingdom."
    },
    {
        id: 34,
        name: "Celebrity Icon #67",
        collection: "Celebrity Icons",
        image: "./resources/nft-34.png",
        price: "8.9",
        currency: "ETH",
        owner: "0x2x4Y5Z6A7B8C9D0E1F2G3H4I5",
        creator: "0x2x4Y5Z6A7B8C9D0E1F2G3H4I5",
        attributes: ["Celebrity", "Icon", "Legend"],
        chain: "ethereum",
        category: "art",
        status: "auction",
        likes: 567,
        views: 3456,
        isNew: false,
        isTrending: true,
        description: "Iconic celebrity captured as digital legend."
    },
    {
        id: 35,
        name: "Art Collection Premium #91",
        collection: "Art Collection Premium",
        image: "./resources/nft-35.jpg",
        price: "5.2",
        currency: "ETH",
        owner: "0x3y5Z6A7B8C9D0E1F2G3H4I5J6",
        creator: "0x3y5Z6A7B8C9D0E1F2G3H4I5J6",
        attributes: ["Premium", "Collection", "Art"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 423,
        views: 2789,
        isNew: false,
        isTrending: false,
        description: "Premium piece from an exclusive art collection."
    },
    {
        id: 36,
        name: "Digital Artist Pro #88",
        collection: "Digital Artist Pro",
        image: "./resources/nft-36.jpg",
        price: "4.1",
        currency: "ETH",
        owner: "0x4z6A7B8C9D0E1F2G3H4I5J6K7",
        creator: "0x4z6A7B8C9D0E1F2G3H4I5J6K7",
        attributes: ["Pro", "Artist", "Digital"],
        chain: "ethereum",
        category: "art",
        status: "new",
        likes: 298,
        views: 1876,
        isNew: true,
        isTrending: false,
        description: "Professional digital art from a skilled artist."
    },
    {
        id: 37,
        name: "Gaming Legend #99",
        collection: "Gaming Legends",
        image: "./resources/nft-37.png",
        price: "7.3",
        currency: "ETH",
        owner: "0x5a7B8C9D0E1F2G3H4I5J6K8L9",
        creator: "0x5a7B8C9D0E1F2G3H4I5J6K8L9",
        attributes: ["Gaming", "Legend", "Epic"],
        chain: "ethereum",
        category: "gaming",
        status: "buy-now",
        likes: 634,
        views: 3678,
        isNew: false,
        isTrending: true,
        description: "Epic gaming legend immortalized as NFT."
    },
    {
        id: 38,
        name: "NFT Collection Elite #76",
        collection: "NFT Collection Elite",
        image: "./resources/nft-38.jpg",
        price: "3.9",
        currency: "ETH",
        owner: "0x6b8C9D0E1F2G3H4I5J6K8L9M0",
        creator: "0x6b8C9D0E1F2G3H4I5J6K8L9M0",
        attributes: ["Elite", "Collection", "Premium"],
        chain: "ethereum",
        category: "art",
        status: "auction",
        likes: 389,
        views: 2456,
        isNew: false,
        isTrending: false,
        description: "Elite piece from a premium NFT collection."
    },
    {
        id: 39,
        name: "Digital Art Collection #55",
        collection: "Digital Art Collections",
        image: "./resources/nft-39.jpg",
        price: "2.6",
        currency: "ETH",
        owner: "0x7c9D0E1F2G3H4I5J6K8L9M0N1",
        creator: "0x7c9D0E1F2G3H4I5J6K8L9M0N1",
        attributes: ["Collection", "Digital", "Art"],
        chain: "ethereum",
        category: "art",
        status: "new",
        likes: 267,
        views: 1654,
        isNew: true,
        isTrending: false,
        description: "Beautiful digital art from an exclusive collection."
    },
    {
        id: 40,
        name: "Crypto Art Universe #44",
        collection: "Crypto Art Universes",
        image: "./resources/nft-40.jpg",
        price: "4.8",
        currency: "ETH",
        owner: "0x8d0E1F2G3H4I5J6K8L9M0N1O2",
        creator: "0x8d0E1F2G3H4I5J6K8L9M0N1O2",
        attributes: ["Universe", "Crypto", "Art"],
        chain: "ethereum",
        category: "art",
        status: "buy-now",
        likes: 445,
        views: 2876,
        isNew: false,
        isTrending: false,
        description: "The entire crypto art universe in one piece."
    }
];
